- README.md
https://github.com/oss2025hnu/reposcore-js/issues/8 점수 공식 및 예시 작성 이슈에 대한 PR입니다.
815b84a00d91fd51c651e84dc2133083fb3bb314
Describe alternatives you've considered
PR 개수와 이슈 개수의 비율을 기반으로 점수로 인정 가능한 최대 개수를 구한 후
각 항목별 배점을 적용하여 최종 점수를 산출합니다.
> [DOC] 점수 산출 공식 추가

- lib/analyzer.js
오타 수정 건으로, 별도의 이슈 없이 PR을 올립니다.
https://github.com/oss2025hnu/reposcore-js/commit/f325e84dc8baaa115a5c5fa8463ba1cc22912baa
analyzer.js 내 collectPRsAndIssues 의 101~107번 라인의 console.log 부분의 오타 부분을 수정하였습니다. ( faeture -> feature)
- 오타 부분 ( faeture 오타 )
```
console.log(
`${key}\n`+ 
`bug and faeture PR : ${value.pullRequests.bugAndFeat}\n`+
`documents PR : ${value.pullRequests.doc}\n`+
`bug and faeture issues : ${value.issues.bugAndFeat}\n`+ 
`documents issues : ${value.issues.doc}\n`)
})
```
> analyzer.js 내 코드 오타 수정

- lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/12 calculateScores 함수 구현 요청 이슈에 대한 PR입니다.
05aa59dc3b53f887657a8797c225ed488ea180a0
https://github.com/oss2025hnu/reposcore-js?tab=readme-ov-file#score-formula 를 참고하였습니다.
> [FEAT] calculateScores 함수 구현

- index.js
- lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/48 [FEAT] 기여자들의 평균 점수를 계산하는 기능 요청에 대한 PR입니다.
bbec14b953f3fed47040c914af9706b7a76f5551
구현 내용
참가자들의 평균 점수를 구할 수 있는 calculateAverageScore() 함수를 구현 및 추가하였습니다.
@taegeon1ee 님의 이슈 요청대로 계산된 평균을 ***total*** 에 추가하였습니다.
> [FEAT] 기여자들의 평균 점수를 계산하는 기능 요청에 대한 PR

- lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/62
[FAET] generateChart로 생성되는 차트의 가독성 개선 요청에 대한 PR입니다.
322aa7d08a42bb770f194d6d46e01d0d176a8fce
구현 내용
차트 함수에 가로 차트로 변경하는 코드를 추가하여 @KohSeungJae 님의 요청사항인 
차트 가독성을 향상시켰습니다.
> [FAET] generateChart로 생성되는 차트의 가독성 개선 요청에 대한 PR

- lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/55 [BUG] 점수가 0점으로 계산되는 버그 수정 요청에 대한 PR입니다.
**Version (commit id)**
https://github.com/oss2025hnu/reposcore-js/commit/416888ced68a93193bd01b4bf21d1f737e098b8f
**변경사항**
- 많은 학생들이 1개의 PR, 1개의 이슈를 작성했음에도 0점으로 표기되는 버그가 있었습니다.
- 이를 해결하기 위해 최소 기준 이상부터 비율을 적용하는 방식으로 수정하였습니다.
기능 PR이 없고 문서 PR만 있을 경우 temp_p_fb = 1로 계산에만 임시 반영으로 수정하였습니다.
p_valid, i_valid 산정에는 반영되나, 기능 PR 점수는 0으로 유지하였습니다.
> [BUG] 점수가 0점으로 계산되는 버그 수정 PR

- lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/92 위 이슈에 관한 PR입니다.
https://github.com/oss2025hnu/reposcore-js/commit/06950c75b8edfe5fcd7d0b5aa27d783e3a9b9021
calculateAverageScore함수가 완전히 동일한 내용으로 두번 정의되어 있어, 하나를 삭제 후 커밋하였습니다.
> [FEAT] 중복된 코드 제거 요청에 대한 PR

- README.md
https://github.com/oss2025hnu/reposcore-js/issues/74 [DOC] 환경변수 등록으로 인한 명령어 수정
에 대한 PR입니다.
https://github.com/oss2025hnu/reposcore-js/commit/df0aa68d5094659eeca80a0cfb63a45ab7312c1f
변경내용
README.md 파일에 다음 내용을 추가하였습니다
- 토큰을 사용한 최초 실행 방법
- .env 파일 자동 생성 및 이후 실행 방법
- 명령어 예시 추
> [DOC] 환경변수 등록으로 인한 명령어 수정 PR

- index.js
https://github.com/oss2025hnu/reposcore-js/issues/97 API 값 중복 저장 방지에 대한 PR입니다.
Specify version (commit id) df0aa68d5094659eeca80a0cfb63a45ab7312c1f
**변경 사항**
이제 다른 gitToken을 입력 하면, 기존에 있던 토큰은 사라지고 새롭게 추가된 토큰이 그 자리를 대체할 것입니다.
> API 값 중복 저장 방지에 대한 PR

- lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/57
에 대한 pr입니다.
-테스트 진행 결과
터미널에 %를 포함한 결과가 생성되었고
아래와 같은 결과를 확인했습니다.
표도 터미널에 생성되었으나 붙여넣기 과정에서 표가 깨져서 생략하였습니다.
@kjason0102 ➜ /workspaces/reposcore-js-kjs (percentage) $ node index.js -r oss2025hnu/reposcore-js -t -f both
토큰 인증을 진행합니다...
토큰이 인증에 성공했습니다.
Collecting data...
Collecting PRs and issues...
***reposcore-js***
bug and Feat PRs : 28
doc PRs : 10
bug and Feat issues : 40
doc issues : 13
reposcore-js Average Score: 7.58
점수 집계 텍스트 파일이 생성되었습니다: /workspaces/reposcore-js-kjs/results/reposcore-js.txt
reposcore-js 점수 집계가 완료되었습니다.
csv_reposcore-js.csv 생성.
차트 이미지가 저장되었습니다: results/reposcore-js_chart.png
reposcore-js.txt 파일의 내용 또한
joon0447 : 46 (23.35%)
KohSeungJae : 28 (14.21%)
Jass2345 : 21 (10.66%)
JosephStalin0305 : 15 (7.61%)
jaewon786 : 14 …
> [FEAT] 기여도 비율 추가 

- package.json
https://github.com/oss2025hnu/reposcore-js/issues/126 에 대한 pr입니다 
해당 부분 삭제 완료하였습니다.
> [BUG] package.json 에 중복된 dependency가 있습니다. 

- index.js
https://github.com/oss2025hnu/reposcore-js/issues/136 에 대한 PR입니다.
Specify version (commit id). 
a1a447e5c2240d00bbf1839be83676fb071b9182
변경 사항
1. 유틸리티 함수 추가
• jsonToMap: JSON 객체를 Map으로 변환
• mapToJson: Map 객체를 JSON 객체로 변환
2. 캐시 처리 함수 수정
• loadCache: 캐시 파일을 읽어 JSON 파싱 후, jsonToMap을 호출하여 Map 객체로 변환하도록 변경했습니다.
• saveCache: Map 객체를 저장할 때 mapToJson 함수를 통해 JSON 객체로 변환 후 파일에 기록하도록 수정했습니다.
> [BUG] 캐시 처리 로직 개선 PR

- index.js
https://github.com/oss2025hnu/reposcore-js/issues/145 [REFACTOR] .env 파일 업데이트 로직 단순화 개선 요청 에 대한 PR입니다.
Specify version (commit id). https://github.com/oss2025hnu/reposcore-js/commit/bb31860d50c6922ffda4d31b7003a2153fc6358a
**변경사항**
- 기존 코드에서 .env 파일에 GitHub 토큰을 저장할 때,
토큰 존재 여부 확인 및 업데이트/추가하는 로직이 중복적으로 사용되고 있었습니다.
이를 개선하기 위해 해당 로직을 updateEnvVariable 유틸리티 함수로 추출하여 중복을 제거하고 가독성을 향상시켰습니다.
- 들여쓰기 부분이 잘 맞지 않아서 맞춰주었습니다.
> [REFACTOR] .env 파일 업데이트 로직 단순화 개선 요청 에 대한 PR

- README.md
- Readme_Template.md
https://github.com/oss2025hnu/reposcore-js/issues/142 package-lock.json 커밋 금지 관련 주의사항 추가 요청에 대한 PR
https://github.com/oss2025hnu/reposcore-js/commit/7b43d9e4e8f2d91a95b7cdfeba8505dcca81f588
**변경사항**
`README.md`에 `package-lock.json` 자동 생성 주의사항 추가
해당 파일은 커밋 금지 대상임을 명시
`git add`, `rm`, `git restore --staged` 등 커밋 방지 방법 예시 포함
> package-lock.json 커밋 금지 안내 추가

- index.js
#156 [BUG] -c 옵션 사용 후 계산 결과 출력 안됨 #156 문제 개선 PR 요청합니다.
https://github.com/oss2025hnu/reposcore-js/commit/33860a2b8f86be9f11d69104c90b1f1d24186ce3
이슈에서 언급 한대로 jsonTomap 함수를 수정하였고 따로 언급했던 135번줄도 수정하였습니다.
> [BUG] -c 옵션 사용 후 계산 결과 출력 안됨 #156 문제 개선 PR 

- index.js
- lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/109  result 디렉터리 생성 코드 개선의 대한 PR 요청
33860a2b8f86be9f11d69104c90b1f1d24186ce3
변경사항
result 디렉터리를 생성하는 코드의 위치를 index.js로 변경하였습니다.
> [REFACTOR] result 디렉터리 생성 코드 개선

- lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/56 이슈에 대한 PR입니다.
https://github.com/oss2025hnu/reposcore-js/commit/d8a6ea11ad63d86934f9629cc384c19aa5bb9f8b
collectPRsAndIssues 함수 내 중복으로 사용되던 참가자 초기화 코드를 
새로운 함수 initParticipant로 분리하였습니다.
> [FEAT] 참가자 초기화 로직 중복 제거에 대한 PR

- index.js
- lib/Utill.js
- lib/analyzer.js
#171
Utill.js 스크립트를 추가했습니다.
스크립트 내부에 log함수를 추가했고, 이를 index.js와 analyzer.js에 import 했습니다.
프로그램 내부에서 직접적으로 작동에 필요하지 않은 코드들 ex) 이번에 추가한 log등 은 Utill.js로 옮길 예정입니다.
이에 관한 Readme 업데이트와 리팩토링 이슈를 올릴 예정입니다.
> [FEAT] 로그 메시지 타임스탬프 추가

- Readme_Template.md
- token_guide/README.md
https://github.com/oss2025hnu/reposcore-js/issues/167 이슈에 대한 PR입니다.
https://github.com/oss2025hnu/reposcore-js/commit/8abffa4afb36659367e351f8c98c135bf9d664b1
Readme_Template.md 와 token_guide/README.md 내
a 태그, img 태그를 마크다운으로 변경하였습니다.
> [DOC] Readme_Template.md,token_guide/README.md html태그로 되어 있는 부분 markdown문법에 맞춰 재작성 필요에 대한 PR

- README.md
- Readme_Template.md
https://github.com/oss2025hnu/reposcore-js/issues/179 에 대한 PR입니다.
https://github.com/oss2025hnu/reposcore-js/commit/7ad31edadcb80979c801c81ac77611c4c6a56312
변경내용
readme.md의 프로젝트 가이드라인 링크를 `docs/project_guidelines.md`로 변경
> readme.md의 프로젝트 가이드라인 링크 수정

- lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/189 이슈에 대한 PR입니다.
https://github.com/oss2025hnu/reposcore-js/commit/c09a7ba7f6c3bcb8ea81f3b3c1f237033600aea1
collectPRsAndIssues 함수 내 예외처리 구문의 error status와 error message가 명확하게 출력되지 않은 부분을 수정하였습니다.
> [FEAT] error.status가 없는 경우 오류 메시지가 누락되어 원인 파악이 어려움에 대한 PR

- lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/180 [BUG] csv파일의 점수 표기 오류에 대한 PR입니다.
Version (commit id)
c09a7ba7f6c3bcb8ea81f3b3c1f237033600aea1
변경사항
수정 전 csv파일에는 [이름, 점수] 만 표기되었습니다.
이 점을 개선하여 csv파일에 [name,feat/bug PR,doc PR,feat/bug issue,doc issue,total] 이 모두 출력됩니다.
> [BUG] csv파일의 점수 표기 오류에 대한 PR

- lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/185 에 대한 PR입니다.
02c833dc6d1dd4a8666b67c564531451f02fde62
변경사항
생성되는 차트의 값이 올바르지 않아 generateChart() 함수 안의 내용을 수정하였습니다.
> [BUG] 생성되는 차트의 값 오류 수정

- index.js
- lib/analyzer.js
#221 
`main()`에서 비동기 메소드를 대기하도록 수정하였습니다.
`transformUserIdToName()` 메소드를 비동기로 변경하였습니다.
비동기 메소드 내에서 동기식 I/O API를 사용하지 않도록 수정하였습니다.
> Fix usage of updateUserInfo() and transformUserIdToName()

- README.md
84cfe3372cef98fa12572e9810c3ab831c18977a
- README.md 26줄 라인 user`s 를 user's 로 변경
> [STYLE] 오타 수정

- lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/188 에 대한 pr입니다.
테스트 후 교수님의 아이디 두개가 정상적으로 제거되어 출력되는 것을 확인했습니다.
> 교수님의 데이터를 실제 기여도 평가에서 제거

- index.js
- lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/230 [FEAT] 불필요한 옵션 정리 --text, --format 에 대한 PR입니다.
Specify version (commit id). bf17518e70ae9e70c32ca10b4d0c1856c9dbcee3
**변경사항**
- __dirname을 ESM 방식으로 수정(버그가 있어서 실행이 안되던 부분 수정하였습니다.) 
- --text옵션을 삭제하고 --format옵션으로 기능을 통일
- both도 all 로 바꿨습니다.
> [FEAT] 불필요한 옵션 정리 --text, --format 에 대한 PR

- index.js
- lib/Util.js
- lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/215 에 대한 pr입니다.
utill 을 util로 변경하였습니다.
'sv-SE 의 스웨덴 로케일을 'ko-KR' 로케일로 변경하였습니다. 
수정 전 : [2025-04-14 22:38:48] reposcore-js 점수 계산 및 테이블 출력이 완료되었습니다.
수정 후 : [2025. 4. 14. 오후 10:44:36] reposcore-js 점수 계산 및 테이블 출력이 완료되었습니다
> Utill.js의 파일명 변경 및 log()의 수정이 필요함 

- lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/243 [FEAT]오타 수정 PR(typo)에 대한 1점 계산 기능 추가 에 대한 PR입니다.
Specify version (commit id). 0089b8231f73ef97e51b70a23c218d88a8219b06
**변경사항**
- 결과 출력에 오타 수정 PR(typo)를 세는 항목을 추가하였습니다.
- 표와 차트에도 바로 반영이 될 수 있도록 만들었습니다.
> [FEAT]오타 수정 PR(typo)에 대한 1점 계산 기능 추가 에 대한 PR

- README.md
- Readme_Template.md
- docs/debug_guide.md
https://github.com/oss2025hnu/reposcore-js/issues/244 [DOC] 디버깅 및 로깅 가이드 문서 추가 요청 에 대한 PR입니다.
f7153a9e896737ff5f1611610352e7337f3b0098
**변경사항**
- @weeksun02 이슈 작성자님이 요청하신대로 작성해보았습니다.
- https://github.com/oss2025hnu/reposcore-js/pull/249 , https://github.com/oss2025hnu/reposcore-js/pull/254
위 두 merge 진행 할 때, Template_Readme.md파일이 누락된 것 으로 보아, 탬플릿을 작성 안하고 바로 README.md에 작성한 것 같습니다. merge된 내용에 맞게 Template_Readme.md를 추가적으로 수정하였습니다.
> [DOC] 디버깅 및 로깅 가이드 문서 추가 요청 에 대한 PR

- README.md
- Readme_Template.md
- docs/esm_guide.md
https://github.com/oss2025hnu/reposcore-js/issues/266 이슈에 대한 PR입니다.
https://github.com/oss2025hnu/reposcore-js/commit/28113932d64f1b1083c32920ee1119117ab21ff7
README.md 내 ESM 전환 안내의 내용을 esm_guide.md 문서로 만들어 분리하였고,
링크로 연결하도록 수정했습니다.
README.md 내 코드 검사 (Lint) 부분 설명의 코드블럭 부분이 닫히지 않은 부분을 수정하였습니다.
> [DOC] README.md안에 있는 내용 정리에 대한 PR

- index.js
https://github.com/oss2025hnu/reposcore-js/issues/268 [REFACT] index.js 내 -r 옵션 검사를 중복으로 하고 있습니다. 에 대한 PR입니다.
Specify version (commit id) 28113932d64f1b1083c32920ee1119117ab21ff7
**변경 사항**
index.js 47번째 라인과 141번째 라인이 중복된 작업을 하고 있으므로, 47번째 라인의 -r 옵션 검사를 삭제하였습니다.
> [REFACT] index.js 내 -r 옵션 검사를 중복으로 하고 있습니다. 에 대한 PR

- lib/analyzer.js
[REFACT] status code 처리가 잘못되어 있습니다. 에 대한 PR요청입니다. https://github.com/oss2025hnu/reposcore-js/issues/271
[ee11af8](https://github.com/oss2025hnu/reposcore-js/commit/ee11af889db4b8ddf753e911ec924f6bbfb5308a)
변경사항
- analyzer.js 161번째 라인 status === 403 && status == 429 -> (status === 403 || status == 429)로 변경하였습니다.
> [REFACT] status code 처리 수정에 대한 PR

- Makefile
- README.md
- Readme_Template.md
https://github.com/oss2025hnu/reposcore-js/issues/248 [BUG] make readme 수정요청 PR입니다.
https://github.com/oss2025hnu/reposcore-js/commit/ee11af889db4b8ddf753e911ec924f6bbfb5308a
**변경사항**
Makefile에서 check-readme 타겟 및 관련 명령 주석 처리
README.md 및 Readme_Template.md 내 check-readme 관련 설명 및 사용법 문서 삭제
> [BUG] make readme 수정요청 PR

- index.js
https://github.com/oss2025hnu/reposcore-js/issues/279 이슈에 대한 PR입니다.
https://github.com/oss2025hnu/reposcore-js/commit/33222e1cc1267420b697999a103e8800324781af
index.js 내 Util.js 와 중복된 함수를 제거하고 Util.js 함수를 index.js 에서 사용하도록 변경했습니다.
> Update index.js[REFACT] index.js에서 Util.js로 넘어간 함수들의 제거 요청에 대한 PR

- README.md
- index.js
- lib/GenerateReadme.js
- lib/analyzer.js
#273 text 포맷이 CSV가 아닌 사람이 보기좋게 정렬된 형태의 txt 파일로 생성
**Specify version (commit id)**
https://github.com/oss2025hnu/reposcore-js/commit/1418a6efc4a02bb0405f20dbed19f94b95ba8849
**변경사항**
- text 포맷이 CSV가 아닌 사람이 보기좋게 정렬된 형태의 txt 파일로 생성하도록 개선
> text 포맷이 CSV가 아닌 사람이 보기좋게 정렬된 형태의 txt 파일로 생성에 대한 PR입니다.

- lib/Util.js
- https://github.com/oss2025hnu/reposcore-js/issues/285
- 로그 레벨 시스템 추가: Util.js에 로그 레벨 시스템을 추가하여 로그 메시지를 LOG, DEBUG, INFO, WARN, ERROR로 구분할 수 있도록 개선했습니다
- 로그 메시지의 가독성 및 중요도 구분이 용이해져 디버깅 및 유지보수가 쉬워집니다.
> [FEAT] 로그 레벨 시스템 추가

- .gitignore
- index.js
- lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/272 [FEAT] user_info.json 파일 생성 기능 추가 제안 에 대한 PR입니다.
Specify version (commit id).  07cbaaf8e855f7f411b8b03ac25f5f556f2e2fba
**변경내용**
- 기존에 있던 -u옵션이 삭제되었을 때, 남아있던 코드들을 수정하여 다시 -u옵션을 사용할 수 있도록 만들었습니다.
> [FEAT] user_info.json 파일 생성 기능 추가 제안 에 대한 PR

- index.js
#305 
index.js 사용하지 않는 PATH변수 두가지를 제거했습니다.
> [REFACT] index.js 내 사용하지 않는 변수 제거

- README.md
- Readme_Template.md
- docs/theme_guide.md
https://github.com/oss2025hnu/reposcore-js/issues/307 [DOC] 테마 기능 사용법 및 themes.json 구조 문서화에 대한 PR입니다.
Specify version (commit id) 175cf6fa046a6df498e9a1d45eee38c66600ea54
**변경 사항**
- theme_guide.md를 만들어 theme에 대해 이해하고, 사용하기 쉽도록 알려주는 가이드를 만들었습니다.
> [DOC] 테마 기능 사용법 및 themes.json 구조 문서화에 대한 PR

- index.js
https://github.com/oss2025hnu/reposcore-js/issues/320
1829ccda3f6292e6f50fd52d00f9f01b33c4cf93
이전 코드에서는 `await analyzer.collectPRsAndIssues()`와 `await saveCache(analyzer.participants)` 부분이 두 곳에서 중복되었지만, 새 코드에서는 한 번만 작성하여 중복 코드를 제거하였습니다.
> [REFACTOR] index.js 구문 최적화에 대한 PR (#320)

- lib/ChartGenerator.js
- lib/analyzer.js
- lib/chartConfig.js
#298 
3c1e2b4
코드 구조 개선:
설정 파일 분리 (chartConfig.js)
차트 생성 로직을 별도 클래스로 분리 (ChartGenerator)
동점자 처리 로직 개선
기능 모듈화:
캔버스 초기화 (_initializeCanvas)
레이블 생성 (_generateLabels)
점수 데이터 추출 (_extractScores)
색상 생성 (_generateColors)
차트 설정 생성 (_createConfiguration)
> [REFACTOR] generateChart() 함수 리팩토링 요청

- index.js
- lib/Util.js
- lib/analyzer.js
[FEAT] Util.js log 단계표시 활성화 #296
ddf539a
b6f2132
- LOG_LEVEL 환경변수를 기준으로 log 출력 필터링
- analyzer.js, index.js 등의 log 호출부에 레벨 명시
- logError는 별도 ERROR 처리 유지
> [FEAT] Util.js log 단계표시 활성화에 대한 PR

- lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/327
0d9ec5ae96ad9b358ff126327af77835dd2ee0b7
오류가 발생한 부분의 잘못된 코드 구조를 수정했습니다
for 루프 내의 비정상적인 return 문을 제거했습니다.
잘못된 닫는 괄호 });를 제거했습니다.
차트 생성 로직을 정리했습니다.
프로그램이 올바르게 실행되는 것을 확인했습니다.
> [BUG] 들여쓰기 / 괄호 버그에 대한 PR (#327)

- lib/analyzer.js
> [BUG] 최초 실행 시 텍스트 파일이 생성되지 않음

- index.js
https://github.com/oss2025hnu/reposcore-js/issues/353
https://github.com/oss2025hnu/reposcore-js/commit/ad3262ea079245acfac79e57e3a9c44ad7fae6cd
CLI의 Usage 부분을 `Usage: index [options] <path..>`에서 `Usage: node index.js [options] <path..>`로 변경
> [BUG] README.md usage부분 수정 요청 PR

- lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/333
23798ab787fe46b6b48870a93151bab8d2d7dad0
- .txt파일 내의 이름이 잘리는 현상이 발견되었다는 이슈의 내용대로 이모지의 이름을 삭제하고 다시 정렬하여 .txt파일을 정리하였습니다.
> [BUG] .txt 파일의 테이블의 규격이 안맞는 버그

- .github/workflows/update-readme.yml
[DOC] README.md 생성 명령을 ci.yaml에 넣어서 깃헙 액션 자동화 #339
c5ad796
GitHub Actions (update-readme.yml)을 이용해 index.js, lib/**, Readme_Template.md 변경 시 자동 실행되며, make readme를 실행한 후 README.md에 변경이 감지되면 자동으로 커밋 및 푸시됩니다.
> [DOC] README.md 생성 명령을 ci.yaml에 넣어서 깃헙 액션 자동화

- lib/ChartGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/367
61689ed94f7f718052a93e653e73edba293905da
그래프에 시간이 제대로 나오지 않는 부분을 한국시간으로 맞추어 수정하였습니다.
> [BUG] 그래프 생성 시 이미지에 나타나는 시간이 현재 시간과 상이함. 에 대한 PR

- README.md
- Readme_Template.md
[DOC] README.md 차트에 대한 추가 설명 https://github.com/oss2025hnu/reposcore-js/issues/380 에 대한 PR입니다.
611d14102822b74c7e7203cea5cd8347d2092531
README.md의 토큰 실행 및 기여도 점수 확인 부분에 공동 순위 계산 방식에 대한 설명을 추가 후 make readme를 통해 최신화함.
> 공동 순위 설명 추가

- lib/ChartGenerator.js
4b1b748243fc93ce1bc70a2d1d6a8ba539c69d47
`ChartGenerator.js` 파일의 56~57번 라인 들여쓰기 오타 수정
> [STYLE] 들여쓰기 오타 수정

- README.md
- index.js
https://github.com/oss2025hnu/reposcore-js/issues/364 README.md의 usage 부분 개선 요청에 대한 PR입니다. 
509d3d0c349f5f8b8c9263beffd95041bbbe7a88
`index.js` 파일의 `program` 옵션에 대한 설명을 한국어로 통일했습니다.
> [STYLE]: 옵션 설명을 한국어로 통일

- index.js
[BUG] 통합 레포지토리 분석 시 특정 로그가 반복되어 출력됨. https://github.com/oss2025hnu/reposcore-js/issues/370 에 대한 PR입니다.
611d14102822b74c7e7203cea5cd8347d2092531
format 옵션이 'all'인 경우 특정 로그를 출력하는 코드가 중복되어 있는 것을 확인하였고, 둘 중 유지보수에 좋은 후자 코드를 살리고 전자 코드를 삭제하여 수정함.
> 저장소 분석 시 특정 로그가 반복 출력되던 현상 수정

- lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/387
1e1054c796f345834992512f65e99fc6e91283bf
테이블 상단에 제목 및 결과 생성 시간을 추가했습니다
> .txt에 결과 생성 시간 추가

- README.md
#378 
7930de5
"통헤" > "통해" 로 오타 수정하였고 가독성을 높이기 위해 중간에 줄바꿈 했습니다.
> README.md 오타 수정

- lib/htmlGenerator.js
[BUG] html에서 csv 파일 다운로드 실패 https://github.com/oss2025hnu/reposcore-js/issues/395 에 대한 PR입니다.
d6355357443040924fb8edee93f922caf53ed09e
기존에 존재하던 ``Download Count CSV``와 ``Download Score CSV``버튼을 ``Download Combined SCV``로 수정하였고, CSV파일이 다운로드 되지 않던 문제 수정
> Csv download 불가 문제 해결

- lib/ChartGenerator.js
#403 
a0285d7
기존 코드를 유지한 채 ChartGenerator.js 파일의 비율 계산 부분에 "이슈 점수의 비율을 계산하는 코드"를 추가하였습니다.
> ChartGenerator.js 이슈 점수 계산 코드 추가

- README.md
- lib/analyzer.js
- lib/csvGenerator.js
- lib/tableGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/388
b5d22647e544905cf930406726c8357938d12b09
analyzer.js에서 테이블과 CSV를 출력하는 부분을 제외 후
tableGenerator.js, CsvGenerator.js를 만들어 분리
> analyzer.js에서 분석 로직과 출력 로직 분리

- lib/ChartGenerator.js
#408 
3d33ed4
차트에 F/D/T/I에 대한 설명 subtitle에 추가
> 차트에 F/D/T/I에 대한 설명 추가

- README.md
- Readme_Template.md
- docs/view_results_guide.md
#415
3ceecd001c747b56cd8181c22c8edc71462019ce
- `results/index.html` 파일을 여는 방법을 별도 문서(`docs/view_results_guide.md`)로 분리하여 작성
- `README.md` 하단에 해당 문서로 연결되는 링크 추가:  
`[HTML 리포트 보기 (results/index.html)](docs/view_results_guide.md)`
> HTML 파일 보는 방법 Readme에 설명

- docs/cherry-pick_guide.md
https://github.com/oss2025hnu/reposcore-js/issues/392
5638694bbdfbd3086b02d07d3532a5aef0909f08
Cherry-Pick 이용에 대한 내용 cherry-pick_guide.md 파일을 만들어 추가
> cherry-pick 가이드 문서화

- .devcontainer/devcontainer.json
#421
1da0b7205fe41ae3324412606d4e25c1f3b30d3f
* devcontainer.json 파일 내 vscode.extensions 항목에 Live Server 확장(ritwickdey.LiveServer)을 추가하였습니다.
> HTML 미리보기를 위한 Live Server 확장 기능 devcontainer에 추가

- results/index.html
https://github.com/oss2025hnu/reposcore-js/issues/424
d915bef8a305b44fb59b0e898e065406a1b232bf
결과 확인하는 result 디렉토리 내 레포지토리 별 디렉토리 분리에 따라 변경된 chart, csv의 경로를 재설정
> 결과 HTML에서 이미지 및 CSV 다운로드 경로 재설정

- README.md
- Readme_Template.md
[DOC] cherry-pick_guide.md로 이동하는 링크 README.md에 추가 https://github.com/oss2025hnu/reposcore-js/issues/426 에 대한 PR입니다.
d915bef8a305b44fb59b0e898e065406a1b232bf
체리픽 기능에 관한 md 파일을 readme.md에 링크한 뒤 make readme 실행함.
> Cherry pick 문서 readme에 링크

- README.md
- Readme_Template.md
[DOC] README.md 결과 리포트(index.html) 확인 가이드 링크 부분 스타일 개선 https://github.com/oss2025hnu/reposcore-js/issues/425 에 대한 PR입니다.
d915bef8a305b44fb59b0e898e065406a1b232bf
readme.md의 html보고서 부분을 다른 md 파일 링크 양식과 통일시켰습니다.
> readme.md의 html 보고서 부분 양식 통일

- .github/workflows/jslint.yml
- package.json
https://github.com/oss2025hnu/reposcore-js/issues/399
https://github.com/oss2025hnu/reposcore-js/commit/d915bef8a305b44fb59b0e898e065406a1b232bf
- jslint를 개발 의존성에 추가
- `.github/workflows/jslint.yml`: Pull Request 시 JSLint 검사를 자동 실행하는 GitHub Actions 워크플로우 파일을 새로 추가
> [FEAT] JSLint를 설정하고 실행하도록 구성 제안 PR

- README.md
- index.js
#447 
3a044b6
--threshold 기능을 추가해 일정 점수 이상인 사용자를 출력할 수 있게 했습니다.
실행 명령어 : node index.js --threshold 50 --format all <저장소 경로>
=> 50점 이상인 사용자들 출력
> index.js --threshold 필터링 기능 추가

- lib/ChartGenerator.js
[FEAT] 차트 데이터 레이블에 Issue ratio(I) 표시 추가 https://github.com/oss2025hnu/reposcore-js/issues/465 에 대한 PR입니다.
51853d4b1a3ded3465d046cd13cdea1fb79bd533
Issue ratio (I)를 추가하여 그래프에 표시되도록 하였습니다.
> Issue ratio(I)를 그래프에 표시

- lib/ChartGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/479
6660d29d162af34eb7e1ad8adc6b25e9ba541353
차트 오른쪽에 여백을 줌으로써 잘림현상 해결
> 차트 오른쪽  잘림현상 해결

- README.md
- Readme_Template.md
#478 
f27a4cc
index.js 파일에 대한 설명을 간단하게 작성하였습니다.
> index.js 설명 추가

- docs/cherry-pick_guide.md
[DOC] cherry-pick_guide.md 코드 수정 https://github.com/oss2025hnu/reposcore-js/issues/494 에 대한 PR입니다.
6660d29d162af34eb7e1ad8adc6b25e9ba541353
요청에 따라 해당 마크다운 파일 모양을 수정, 특정 내용은 더 내용이 와닿을 수 있도록 표현 수정
> cherry-pick_guide.md 파일 양식 수정

- lib/htmlGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/428
7eaba7acba05dc006c194fda1c1f78e72b822cbf
html에 txt 파일 다운로드 추가
> [FEAT] html에 txt 파일 다운로드 추가

- README.md
- Readme_Template.md
https://github.com/oss2025hnu/reposcore-js/issues/502
https://github.com/oss2025hnu/reposcore-js/commit/ac062488e02383631b585744a029d9ec48d2c458
readme에 github api 가이드 문서 링크 추가
> readme에 github api 가이드 문서 링크 추가

- README.md
- Readme_Template.md
- index.js
#515 
f57aa6e
Readme_Template.md에 누락된 Github API 가이드 설명을 한 줄로 간단하게 추가하였습니다
> Readme_Template.md 누락된 설명 추가

- lib/csvGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/519
ac138a381ce3150406f7e4973c8fbf249057b766
generateCombinedCsv() 함수 안 내용을 추가하여 문제를 해결하였습니다.
> [BUG] CSV 파일에 헤더만 출력되고 데이터가 누락되는 오류 해결

- index.js
- lib/analyzer.js
- lib/csvGenerator.js
- lib/tableGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/439
https://github.com/oss2025hnu/reposcore-js/commit/194aa6b2a43d8480ec97747e40b0314cc454b2f6
- 저장소별 평균 점수, 결과 파일 목록을 한 번에 출력
- 불필요한 중복 로그 제거 (텍스트/CSV 생성 메시지 등)
- 전체 저장소 수 및 분석 완료 메시지 정리
- 추후에 분석할 내용이 많아질 경우 레포지토리 별로 분리 되어있는, 아래의 결과가 더 가독성이 좋다고 판단
`node index.js oss2025hnu/reposcore-py oss2025hnu/reposcore-js oss2025hnu/reposcore-cs`를 입력했을 시
```
[2025 05 22 오후 07:25] ℹ️ [INFO] 현재 테마: 'default'
[2025 05 22 오후 07:25] ℹ️ [INFO] 캐시를 사용하지 않습니다. 데이터를 새로 수집합니다.      
[2025 05 22 오후 07:25] ℹ️ [INFO] Collecting PRs and issues...
[2025 05 22 오후 07:25] ℹ️ [INFO] total Average Score: 13.26
[2025 05 22 오후 07:25] ℹ️ [INFO] reposcore-py Average Score: 5.96
[2025 05 22 오후 07:25] ℹ️ [INFO] reposcore-js Average Score: 12.77
[2025 05 22 오후 07:25] ℹ️ [INFO] …
```
> [FEAT] 다중 저장소 분석 시 콘솔 출력 가독성 향상 PR

- index.js
https://github.com/oss2025hnu/reposcore-js/issues/530
a4845b936cc0553aaafb465af8cccc961f84f14c
total폴더가 생성되지 않고 total분석 또한 생성되지 않는 상황
ndex.js의 255번줄 코드 if (repoName === 'total') continue; 제거 함으로써 total폴더 및 total 자료들이 생성
> [BUG] total 분석이 생성되지 않는 문제 

- lib/htmlGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/532
f71fc58497ae754f1d8fe765779936ab6b795456
HTML 테이블의 총점 열을 굵은 글씨로 표시 하여 가독성을 개선하였습니다.
> HTML 테이블 총점 가독성 개선 

- index.js
https://github.com/oss2025hnu/reposcore-js/issues/534 에 대한 PR입니다.
fdc216362f4eb1cd53ff38f49f191ab0876dac7c
요청해주신 내용을 바탕으로 마지막 total 정보를 뒤쪽으로 이동하도록 수정하였습니다.
total 정보가 터미널 상 가장 마지막에 출력할 뿐만 아니라 기존에 중복되었던  total에 관한 log 또한 한번만 출력되도록 수정하였습니다.
> 로그 출력에서 중복된 "Total" 표시 개선 요청에 대한 PR

- lib/csvGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/535
e348462581036e1c6013e9b55a78a85bca097a83
총점을 기준으로 내림차순으로 정렬되어 출력하도록 변경
> [FIX] csv파일 내림차순으로 정렬

- lib/htmlGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/536
fdc216362f4eb1cd53ff38f49f191ab0876dac7c
표 제목이 가장 위에 표시되도록 수정, 그 아래에 평균 점수, 최저 점수, 최고 점수를 순서대로 출력
> html 표 순서 정리

- README.md
- index.js
[BUG] 중복된 테마 옵션 제거 및 정리 https://github.com/oss2025hnu/reposcore-js/issues/548 에 대한 PR입니다.
ad51d0a31e3f0a855606a47c3b4fe95cae13e7ed
기능이 중복되고 작동되지 않던 -change-theme 옵션을 제거했습니다.
> --change-theme 옵션 기능 제거

- README.md
- index.js
https://github.com/oss2025hnu/reposcore-js/issues/545
https://github.com/oss2025hnu/reposcore-js/commit/ad51d0a31e3f0a855606a47c3b4fe95cae13e7ed
-u 옵션이 무엇을 하는지에 대한 설명을 구체적인 내용으로 수정하였습니다.
-u 옵션 사용 시 user_info.json 파일이 필요하다는 것을 사용자들이 인지할 수 있도록 내용을 추가했습니다.
> --user-name 옵션 도움말 개선 필요에 대한 PR
