lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/3 해당 이슈에서의 버그를 수정했습니다.
**Version (commit id)**
5dccfba692a82a9f3383128c5faa77e710fc68a4
--repo 옵션 형식을 함수에 맞게 변경하지 않아 발생한 버그였습니다.
옵션의 user/repo 형식을 유지하고, coollectsPRs 함수의 내용을 변경하여 해결했습니다.
=> [BUG] 실행시 오류가 발생하던 문제 수정

index.js, lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/6 해당 이슈의 collectIssues 함수 수정 요청에 대한 PR입니다.
**Specify version (commit id).**
945573ef7b78a83ea1ba4214b2b2bab7d2f2e94a
**구현내용**
이슈를 수집하는 collectIssues 함수 구현 도중, PR또한 이슈의 일종이라는 것을 알게 되어 기존의 collectPRs를 제거 후 PR과 이슈를 한번에 처리하는 collectPRsAndIssues 함수를 구현하였습니다. 
라벨이 없는 PR과 이슈는 합산되지 않으며,  라벨을 통해 버그/기능, 문서로 나누어 수집하였습니다. 이로 인해 participants의 각 엔트리가 다음과 같이 변경되었습니다.
```
사용자 => {
pullRequests : {bugAndFeat : 0, doc : 0}, 
issues : {bugAndFeat : 0, doc : 0}, 
comments : 0
}
```
participants의 구조가 변경되어 아직 구현되지 않은 calculateScores 함수의 더미 코드에서 오류가 발생하여 아직 구현되지 않은 
함수의 더미 코드는 주석 처리를 하였고, '함수가 아직 구현되지 않았습니다'를 출력하도록 하였습니다.
=> collectIssues 함수 수정 요청에 대한 PR

README.md, index.js, lib/analyzer.js, package-lock.json
https://github.com/oss2025hnu/reposcore-js/issues/9 이슈의 인증 기능 구현 요청에 대한 PR입니다.
https://github.com/oss2025hnu/reposcore-js/commit/815b84a00d91fd51c651e84dc2133083fb3bb314
- 토큰 인증 옵션 추가
-a ( --api-key) <token> 으로 깃허브 토큰을 인증할 수 있는 옵션을 추가하였습니다.
해당 옵션으로 토큰을 인증하여 인증 성공 시, 인증 상태로 프로그램을 사용하며, 
옵션 미사용 시 미인증 상태로 프로그램을 사용합니다.
입력된 토큰의 유효 여부도 확인하여 여부에 따라 다음과 같은 메시지를 출력합니다.
**(토큰 입력 없이 사용 시)**
**(유효한 토큰 입력 시)**
**(비정상적인 토큰 입력 시)**
- README.md 수정
새로운 옵션의 추가에 따라, README.md의 Usage의 Options에 다음과 같은 문구를 추가하였습니다.
```
-a, --api-key <token>, Github Access Token (optional)
```
=> [FEAT] 선택적 인증 기능 구현 요청에 대한 PR

lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/32 [FEAT] generateChart 함수 구현 에 대한 PR입니다.
eea5320c969f7f5f0a62c95286efc1ffc6372985
구현 내용
-  calculateScores 함수와 generateTable함수가 구현 되면서 generateChart함수를 작성할 수 있었습니다.
-  @Sernn0 님이 이슈내용에서 요청한 "ASCII 기반의 바 차트 또는 그래프 형태로 점수를 표현하면 좋을 것 같습니다."에 맞춰서 generateChart 함수를 calculateScores 함수에서 계산된 점수를 바탕으로, 참가자 별 기여도를 ASCII 기반 막대 그래프로 시각화하였습니다.
바는 █ 문자로 구성되며, 점수에 따라 상대적인 길이로 표현됩니다. 이름과 점수를 함께 표시하여 명확성을 높였습니다.
-  그래프도 표와 마찬가지로, 계산된 점수를 내림차순으로 정렬하여 고득점자부터 표시하였습니다.
=> [FEAT] generateChart 함수 구현 에 대한 PR

index.js, lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/33 이슈의 PR입니다.
https://github.com/oss2025hnu/reposcore-js/commit/1f4d9fa2ef37b20bd6643f928a02c16d6fbf6b1a
- 잘못된 repo 주소 입력 시 에러문 수정
try-catch 문을 사용하여 입력된 repo의 주소가 잘못 되어 404 오류가 발생 시, repo 주소가 잘못되었다는 에러문을 한글로 수정하여, 사용자들이 더 쉽게 이해할 수 있도록 수정하였습니다.
- -r(--repo) 옵션 미입력시 에러문 수정
기존 영문으로 출력되던 에러문을 한글로 수정하여 -r 옵션이 필수임을 명시하고, 자동으로 -h 옵션이 실행되도록 하였습니다.
=> [FEAT] 저장소 주소 입력의 형식 검사 구현 요청에 대한 PR 

index.js, lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/18 해당 이슈의 다중 저장소 분석 구현 요청에 대한 PR입니다. 
bbec14b953f3fed47040c914af9706b7a76f5551
**구현내용**
명령줄 인자의 -r 값을 여러 값을 받도록 변경하였고, 공백으로 구분해 입력합니다. 해당 주소들은 this.repoPaths 에 저장되며, collectPRsAndIssues 함수에서 for (const repoPath of this.repoPaths) 사용해 모든 주소에 대한 데이터 수집을 진행했습니다.
기존의 하나의 저장소의 데이터만 저장하던 participants의 구조가 다음과 같이 변경되었습니다.
```
{
'total' => 
'user1' => { pullRequests: {bugAndFeat : 0, doc : 0}, issues: {bugAndFeat : 0, doc : 0} },
'user2' => { pullRequests: {bugAndFeat : 0, doc : 0}, issues: {bugAndFeat : 0, doc : 0} }}
'repo1' => {
user1' => { pullRequests: {bugAndFeat : 0, doc : 0}, issues: {bugAndFeat : 0, doc : 0} },
user2' => { pullRequests: {bugAndFeat : 0, doc : 0}, issues: {bugAndFeat : 0, doc : 0} }},
'repo2' …
```
=> [FEAT] 다중 저장소 분석 구현

.gitignore
#65 [DOC] gitignore 파일에 score_table.txt 추가
**Specify version (commit id)**
https://github.com/oss2025hnu/reposcore-js/commit/6d24151e5421196f1a7005907a7572b5c58d9152
**변경내용**
- `.gitignore` 파일에 추적하지 않아야 할 파일을 추가 했습니다.
=> [DOC] gitignore 파일에 score_table.txt 추가

lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/64 이슈에 대한 PR입니다.
https://github.com/oss2025hnu/reposcore-js/commit/6d24151e5421196f1a7005907a7572b5c58d9152
generateChart 함수 내에서 차트 이미지를 저장하기 전에 차트 이미지 파일이 저장될 폴더가 있는지 확인합니다.
확인 후 존재하지 않으면, 폴더 생성 후 이미지를 저장하도록 변경하였습니다.
=> [BUG] --output 디랙토리가 생성되지 않은 경우 차트 이미지 생성에 실패함에 대한 PR

index.js
https://github.com/oss2025hnu/reposcore-js/issues/90 [FEAT] 불필요한 코드 제거 요청 에 대한 PR입니다.
06950c75b8edfe5fcd7d0b5aa27d783e3a9b9021
**구현내용**
program.help() 는, 도움말을 출력한 후 프로세스를 종료하기 때문에 process.exit(1) 가 필요하지 않을 뿐더러, 해당 코드가 실행되지도 않기 때문에, 삭제 후 커밋하였습니다.
=> [FEAT] 불필요한 코드 제거 요청 에 대한 PR

README.md, index.js
--format 옵션 값 유효성 검사 기능 추가 https://github.com/oss2025hnu/reposcore-js/issues/87 에 대한 PR 입니다.
**Specify version (commit id).**
06950c75b8edfe5fcd7d0b5aa27d783e3a9b9021
**변경사항**
- CLI에서 --format 옵션으로 입력 가능한 값을 제한하는 유효성 검사 로직을 추가했습니다.
- 허용값은 `table`, `chart`, `both`, `csv` 이며, 해당 값 외의 입력이 들어오면 명확한 에러 메시지를 출력하고 프로그램을 종료합니다.
=> index.js에서 --format 옵션 값 유효성 검사 PR

index.js, lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/36 해당이슈의 csv파일을 생성하는 함수 구현에 대한 PR입니다.
06950c75b8edfe5fcd7d0b5aa27d783e3a9b9021
**구현내용**
--format  값에 table 을 선택시 각 이름과 점수를 담고있는 csv파일을 생성하는 generateCsv 함수를 구현하였습니다.
각 csv 파일은 result 디렉터리에 생성됩니다.
=> [FEAT] generateCsv 함수 구현

index.js, lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/89 유효하지 않은 토큰 값이 env 파일에 저장됩니다 에 대한 PR입니다.
06950c75b8edfe5fcd7d0b5aa27d783e3a9b9021
- 토큰의 값을 환경변수에 저장하기전, 입력된 토큰 값이 유효한 값인지 확인을 한 뒤,
유효한 값이라면 저장을, 유효하지 않은 값이라면 저장을 하지 않고 경고문을 출력 후 프로그램을 종료합니다.
=> [FIX] 유효하지 않은 토큰을 .env에 저장하지 않도록 개선

lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/96 에 대한 PR입니다.
https://github.com/oss2025hnu/reposcore-js/commit/06950c75b8edfe5fcd7d0b5aa27d783e3a9b9021
-t 옵션을 사용하여 생성되는 텍스트 파일의 파일명을 대상 레포지토리의 이름에 따라 변경되도록 하였습니다.
예 ) reposcore-py 대상 텍스트 파일 -> reposcore-py.txt
reposcore-js 대상 텍스트 파일 -> reposcore-js.txt
=> [FEAT] generateTable 함수의 txt 파일 생성이 이루어지지 않음에 대한 PR

lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/81
[BUG] 실행 후 출력되는 .png의 글자가 깨짐 및 내용 다 안보임 문제에 대한 PR입니다.
Version (commit id)
416888ced68a93193bd01b4bf21d1f737e098b8f
구현 내용
1. 글꼴 깨짐 현상이 있어 영어로 수정하였습니다.
2. 참가자의 수가 늘어나도 차트 높이가 고정되어 있어 chart.png 파일에 반영이 안되는 현상이 있었습니다. 
참가자 수 당 높이를 지정하여 차트 높이가 늘어나도록 수정하였습니다.
=> [BUG] 실행 후 출력되는 .png의 글자가 깨짐 및 내용 다 안보임 문제에 대한 PR

lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/116 repoMap, totalMap 에서 사용되지 않는 comments 삭제에 대한 PR입니다
063a5118651338dfcca14df2e49e9b2502813c77
##
변경사항
- analyzer.js 파일의 collectPRsAndIssues 함수에서 사용하지 않는 comments 프로퍼티 삭제
=> [REFACTOR] 사용하지 않는 property 삭제

index.js, package.json
#168[FEAT]Unittest 라이브러리 jest도입
개선 사항
1. 이슈에서 요청한데로 Jest 도입하기 위해 Jest를 프로젝트에 설치하고, package.json에 테스트 스크립트를 추가했습니다:
2. 모든 코드가 한 파일(index.js)에 포함되어 있었으며, Jest로 테스트할 때 CLI 실행 로직이 함께 실행되는 문제가 있어서 
해당 문제를 해결하기 위해서 require.main === module 조건을 추가해 CLI로직과 유틸리티 함수를 분리하여 문제를 해결 하였습니다.
3. 테스트로는 jsonToMap과 mapToJson 변환 테스트 기능과 .env파일에 토큰을 저장하는 것과 업데이트하는 로직의 기능테스트 그 외에도 데이터를 캐싱하고 불러오는 로직까지 테스트 가능합니다.
4. 실제 파일 시스템이나 외부 API 호출을 이용하는 것이 아닌 Mocking을 활용하여 실제 파일을 생성하거나 수정하지 않고, 가상의 파일을 생성하여 테스트를 할 수 있도록 했습니다.
=> [FEAT]Unittest 라이브러리 jest도입#168

README.md, Readme_Template.md
https://github.com/oss2025hnu/reposcore-js/issues/141
해당 issue에 대한 pr입니다.
- Readme_Template.md에 generate-readme 스크립트의 역할과 실행법을 문서화했습니다.
- CLI 옵션이 바뀔 때마다 해당 스크립트를 실행해야 함을 명시했습니다.
- 사용 방법, 템플릿 위치, 주의사항을 모두 포함하여 누구든 활용할 수 있게 했습니다.
=> [DOC] README 자동 생성 기능에 대한 사용법 문서화 필요 

README.md, Readme_Template.md
[DOC] Utill.js 설명 Readme 추가 https://github.com/oss2025hnu/reposcore-js/issues/184 에 대한PR
https://github.com/oss2025hnu/reposcore-js/commit/7c02a8e3b96fb450e097c036bb16f459998ad775
**변경사항**
- `README.md`에 Util.js 도입에 따른 설명 추가
- 해당 내용을 README에 문서화하여 유지보수성 향상
=> Util.js 함수 분리 내용 README에 추가

lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/195 에 대한 pr입니다.
시간로그에 의해 표 윗부분이 밀리는 현상을 해결했습니다.
또한 완료 메세지 출력을 수정하여 표가 출력되기 전이 아닌 표가 출력되고 나서 완료 메세지가 출력될 수 있도록 위치를 변경해 주었습니다.
=> [BUG] 테이블 깨짐 개선 요청 

lib/Utill.js
타임스탬프 UST -> KST로 변경
https://github.com/oss2025hnu/reposcore-js/issues/197 에 대한 PR 요청입니다.
5f54a6e046875faaaa0c67b85e6242410ea1d948
변경사항
fix: log 함수에서 UTC 대신 Asia/Seoul(KST) 시간 사용하도록 변경
=> 타임스탬프 UST -> KST로 변경 

index.js, lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/101
'fs/promises'를 통해 비동기로 처리하도록 개선하였습니다.
커밋 로그 많이 남기지 않으려고 `cherry-pick` 후, `force-push` 했는데, 다음에는 직접 머지 컨플릭트를 해결해야겠습니다...
=> Use 'fs/promises' for filesystem operations

lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/216
446df42
변경사항: 4글자 이상의 한글이름과 영문이름이 마스킹 되도록 수정.
=> 4글자 이상의 한글 이름과, 영문 이름이 제대로 마스킹 처리되지 않음 수정

README.md, Readme_Template.md
https://github.com/oss2025hnu/reposcore-js/commit/50acb8d5d6b72498a007effb59a52ed8c11136b8
**변경사항**
clean 사용방법에서 코드 블록이 작은따옴표 세 개(`'''`)로 잘못 감싸져 있어 마크다운에서 제대로 렌더링되지 않는 문제가 있었습니다.
- '''bash...''' → \`\`\`bash...\`\`\`로 수정하여 코드 블록이 정상적으로 보이도록 변경했습니다.
=> 오타수정 - 잘못된 코드 블록 표기 ('''bash → ```bash) 수정

lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/220 에 대한 PR입니다.
https://github.com/oss2025hnu/reposcore-js/commit/9263d4b3c027ae14389fe1e40b0cabbd23d496e2
chart, csv가 생성될때 생성된 시간을 상단에 표시하였습니다.
**chart**
**csv**
```
Generated at 2025. 4. 14. 오후 12:01:17
name,feat/bug PR,doc PR,feat/bug issue,doc issue,total
joon0447,30,4,32,6,72
KohSeungJae,18,0,18,1,37
jaewon786,12,4,10,0,26
Jass2345,15,2,8,1,26
Jae-Hyuk-Lee,12,2,8,3,25
bym010312,6,10,6,1,23
JosephStalin0305,6,2,12,3,23
kjason0102,9,2,4,2,17
hyunsang1021,9,0,6,2,17
sangmyoung0,6,0,10,0,16
```
=> 분석 결과 파일에 생성 일시 삽입 기능 제안에 대한 PR

index.js, lib/checkLimit.js
[FEAT] GitHub API 남은 요청 횟수 확인 기능 https://github.com/oss2025hnu/reposcore-js/issues/164
필요한 파일만 다시 추려서 작성했습니다.
30e7d27
변경사항
--check-limit 옵션 등록
checkLimit.js 모듈 추가
=> [FEAT] GitHub API 남은 요청 횟수 확인 기능 수정

lib/analyzer.js
#50 
깃허브 API횟수 제한 / 트래픽 문제로는 403, 429 오류가 발생한다고 합니다.
Error 스테이터스가 403, 429일 경우 throw하도록 했습니다.
에러 메세지로는 
⚠️ GitHub API 사용 횟수 제한에 도달했습니다 ⚠️"
"다음 방법 중 하나를 선택하여 해결할 수 있습니다:"
"1. GitHub 토큰을 사용하여 실행 (-a 옵션 사용)"
"2. 캐시된 데이터 사용 (-c 옵션 사용)"
"3. 잠시 후 다시 시도"
을 넣어 두었습니다.
=> [BUG] API 횟수 제한 및 문제 발생 시 오류 문구 및 파일 덮어 쓰기 버그

lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/129 해당 이슈에 대한 PR입니다.
bf17518e70ae9e70c32ca10b4d0c1856c9dbcee3
구현내용
participants를 초기화 하는 과정에서 오타수정에 해당하는 typo를 추가하였습니다.
collectPRsAndIssues함수에서 typo레이블을 구분하는 코드를 추가하였습니다.
=> [FEAT]단순 오타 수정 PR과 내용 추가/재구성 PR 의 구분 구현

index.js
- ESM 환경(Codespace)에서 발생하는 `require is not defined` 오류 해결
- `require('@octokit/rest')` → `import { Octokit }`로 변경
- 조건문 내부에서의 동적 로딩 제거하고 `import`를 상단으로 이동
- `.env` 자동 저장 및 토큰 유효성 검증 기능 유지
- Codespace에서 `node index.js -r oss2025hnu/reposcore-js -a <토큰>` 실행 시 정상 작동 확인
- `.env` 자동 생성 확인
- 점수 계산, CSV/차트 출력까지 완료됨
- https://github.com/oss2025hnu/reposcore-js/issues/251
=> [FIX] ESM 환경에서 require 오류 해결 (#251)

index.js, lib/analyzer.js
- https://github.com/oss2025hnu/reposcore-js/issues/257
- CSV 생성 로직을 `generateScoreCsv`와 `generateCountCsv` 메서드로 분리
- 점수 집계와 활동 개수 집계 CSV 파일의 구조 통일
1. CSV 생성 로직 분리
- `generateScoreCsv`: 점수 기반 CSV 생성 (점수 총합 포함)
- `generateCountCsv`: 활동 개수 기반 CSV 생성 (활동 총합 포함)
- `generateCsv`: 두 메서드를 조율하는 메인 메서드
2. 코드 개선
- CSV 헤더 중복 제거를 위한 `CSV_HEADER` 상수 도입
=> [FEAT] PR/ISSUE 개수 CSV 생성 기능 추가 (#257)

lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/260
차트의 가독성을 개선하기 위해 흰색 배경 적용 기능을 추가했습니다
1. 프로그램을 실행하여 차트 생성
2. 생성된 차트에서 다음 사항 확인:
- 흰색 배경의 차트가 올바르게 생성되는지
=> [FEAT] 차트 가독형 향상을 위한 흰색 배경 기능 추가 (#260)

lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/275
현재 프로젝트의 출력 형식이 일관되지 않아 발생하는 사용자 혼란을 해결하기 위해 다음과 같이 표준화를 진행했습니다:
기존:
- 점수 CSV: `csv_{repoName}.csv`
- 활동 개수 CSV: `activity_count_{repoName}.csv`
변경:
- 점수 CSV: `{repoName}_score.csv`
- 활동 개수 CSV: `{repoName}_count.csv`
- 시간 형식: `[YYYY-MM-DD 오전/오후 HH:MM]`
- 메시지 구조: `[시간] {파일 유형} 파일이 생성되었습니다: {파일 경로}`
예시:
```bash
[2025-04-17 오후 03:30] 점수 집계 CSV 파일이 생성되었습니다: results/reposcore-js_score.csv
[2025-04-17 오후 03:30] 활동 개수 CSV 파일이 생성되었습니다: results/reposcore-js_count.csv
```
1. 프로그램 실행:
```bash
node index.js -r oss2025hnu/reposcore-js
```
2. 확인 사항:
- `results` 디렉토리에서 생성된 파일명이 새로운 규칙을 따르는지 확인
- 콘솔에 출력되는 모든 로그 메시지가 통일된 형식을 따르는지 확인
- 시간 형식이 `[YYYY-MM-DD 오전/오후 HH:MM]` 패턴으로 일관되게 표시되는지 확인
- 파일명의 일관성으로 파일의 용도를 직관적으로 이해할 수 있음
- 통일된 로그 메시지 형식으로 생성 상태를 빠르게 …
=> [REFACT] 출력 형식 표준화 - 파일명 형식 통일, 로그 메시지 형식 통일

index.js, lib/ThemeManager.js, lib/Util.js, lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/287
- ThemeManager 클래스를 통한 테마 관리 구현
- 테마 설정을 JSON 형식으로 저장하고 불러오는 기능
- 다양한 시각적 요소에 대한 스타일 지정 가능
- 기본 테마(default): 밝은 배경과 가독성 높은 색상 구성
- 다크 테마(dark): 어두운 배경과 눈의 피로도를 줄이는 색상 구성
- 사용자가 JSON 형식으로 직접 테마를 정의하고 저장할 수 있음
- 차트 색상, 표 스타일, 텍스트 색상 등을 자유롭게 설정 가능
- 한 번 생성한 테마는 themes.json 파일에 저장되어 재사용 가능
다음 명령어로 테스트할 수 있습니다:
1. 기본 실행:
```bash
node index.js -r oss2025hnu/reposcore-js
```
- 내장 다크 테마 적용
```bash
node index.js -r oss2025hnu/reposcore-js --change-theme dark
```
2. 커스텀 테마 생성 및 적용:
```bash
node index.js -r oss2025hnu/reposcore-js --create-theme '{"name":"vibrantTheme","theme":{"colors":{"primary":"#FF00FF","secondary":"#00FFFF","background":"#1A1A2E","text":"#E94560"},"table":{"head":["cyan"],"border":["magenta"]},"chart":{"backgroundColor":"#1A1 …
```
=> [FEAT] 테마 매니저 기능 구현에 대한 PR

lib/Util.js
https://github.com/oss2025hnu/reposcore-js/issues/297
Util.js의 로그 출력 방식을 차별화하여 로그 메시지를 각 로그 레벨에 따라 다른 형식과 색상으로 출력되도록 설정했습니다.
- 프로젝트를 실행하고 다양한 로그 레벨을 테스트합니다.
```
node -e "import { log } from './lib/Util.js'; log('기본 로그 메시지'); log('디버그 정보입니다', 'DEBUG'); log('일반 정보입니다', 'INFO'); log('경고 메시지입니다', 'WARN'); log('오류가 발생했습니다', 'ERROR');" --input-type=module
```
- 각 로그 레벨이 올바르게 출력되는지 확인합니다.
다음과 같은 결과를 확인할 수 있습니다.
```
[2025 04 19 오전 07:11] 📝 [LOG] 기본 로그 메시지
[2025 04 19 오전 07:11] 🔍 [DEBUG] 디버그 정보입니다
[2025 04 19 오전 07:11] ℹ️ [INFO] 일반 정보입니다
[2025 04 19 오전 07:11] ⚠️ [WARN] 경고 메시지입니다
[2025 04 19 오전 07:11] 🚨 [ERROR] 오류가 발생했습니다
```
=> [FEAT] Util.js 로그 레벨별 출력 방식 차별화 기능 구현에 대한 PR

lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/308 이슈에 대한 PR입니다.
https://github.com/oss2025hnu/reposcore-js/commit/2c40dc21933fdc1331d2b519c0768f49a772c5cf
생성되는 차트의 막대가 짤리는 현상을 방지하기 위해, x축의 최댓값을 
점수의 최댓값+20 으로 동적으로 설정되도록 수정하였습니다.
=> [BUG] 차트에서 1등의 점수가 막대 너비를 초과하여 잘리는 현상에 대한 PR

lib/Util.js, lib/analyzer.js
[FEAT] 기여자 뱃지 시스템 추가 (https://github.com/oss2025hnu/reposcore-js/issues/286#top)
#286 에 대한 pr요청입니다.
1fc1cd9
- 기여자의 총점에 따라 점수 구간별 뱃지(이모지 + 칭호)를 표시하는 기능을 추가했습니다.
- 기존 출력 구조는 유지하되, 이름 앞에 뱃지를 붙여 콘솔 및 텍스트 출력에서도 반영됩니다.
- 점수는 총점을 기준으로 11개 구간으로 나뉘며, `lib/util.js`의 getBadge() 함수를 통해 관리됩니다.
- 출력 대상은 generateTable() 내 table.push()에서 `name`을 `badge + name` 형태로 변경하여 적용하였습니다.
=> [FEAT] 기여자 뱃지 시스템 추가

lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/310
https://github.com/oss2025hnu/reposcore-js/commit/1829ccda3f6292e6f50fd52d00f9f01b33c4cf93
참가자의 점수가 동점일 시, 공동 순위로 처리하게 하였습니다.
=> [FEAT] 동점자에 대한 동일 순위 처리 기능 추가에 대한 PR

index.js, lib/htmlGenerator.js, package.json
--format all 옵션 시 통합 HTML 리포트 생성 기능 추가 #322
f51037b
3832ac0
lib/htmlGenerator.js 파일 생성됨
report.html 자동 생성 기능 추가 (차트 + 테이블 + CSV 링크 포함)
--format all 옵션에서만 생성되도록 조건 설정 (그러나 default가 all로 되어있음)
npm run report 명령어로 브라우저에서 열람가능 ( http-server 실행 되고 report.html 링크를 타고 통합 파일 열람 )
=> [feat] --format all 옵션 시 통합 HTML 리포트 생성 기능 추가 #322

index.js, lib/htmlGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/322
https://github.com/oss2025hnu/reposcore-js/commit/b2255b64b93f4ff43fb6f28e0dc7fc52fcab7f16
- 여러 저장소 리포트를 탭 인터페이스로 구성
- 차트는 왼쪽,  테이블은 오른쪽에 나란히 표시되도록 정렬
- csv 다운로드 링크를 버튼으로 변경
=> HTML 리포트 생성 기능 개선

lib/ChartGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/342
https://github.com/oss2025hnu/reposcore-js/commit/5e42950e751f19c9ce0158c7340a4ef1ea2431cc
차트 Y축의 순위, ID 표시의 순서를 ID, 순서로 변경하여 가독성을 향상시켰습니다.
=> [FEAT] 차트에서 "순위 이름" 대신 "이름 순위"로 나타나도록 변경에 대한 PR

lib/ChartGenerator.js
[FEAT] 그래프에 DOC/FEAT/BUG 점수 비율 텍스트 추가 #303
6d23bd4
- 점수 옆에 총점 + FEAT/DOC/TYPO 비율을 표시하도록 ChartGenerator.js 수정
- 이름과 점수에 숨겨진 ANSI 색상코드 제거(깨짐 방지) 처리 추가
- 총점이 0일 때 비율 계산 에러를 막는 예외처리 추가
=> [FEAT] 그래프에 DOC/FEAT/BUG 점수 비율 텍스트 추가

lib/ChartGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/350
https://github.com/oss2025hnu/reposcore-js/commit/7aa2373daf3d6dd38d220afce9efbbd4d9344862
일부 환경에서 차트 이미지의 한글이 깨지는 현상을 수정하였습니다.
'점' 이라는 한글 대신 영문 'pts'로 출력하도록 변경하였습니다.
=> [BUG] 기여도 그래프에 c810 코드 표시 오류 수정 요청에 대한 PR

lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/341
7aa2373daf3d6dd38d220afce9efbbd4d9344862
참여횟수 count 관련 csv 테이블와 점수 관련 csv 테이블이 두가지 파일로 각각 따로 생성되고있는 것을 하나로 합쳤습니다.
=> [REFACT] 참여횟수 count 관련 csv 테이블와 점수 관련 csv 테이블을 통합합니다 에 대한 PR

index.js
https://github.com/oss2025hnu/reposcore-js/issues/355
ad3262ea079245acfac79e57e3a9c44ad7fae6cd
--create-theme 옵션이 두 번 등장하고 있으며, <theme>와 <json>으로 표기된 인자도 모호하게 겹치고 있는 부분 수정
=> [DOC] README.md 내 중복 CLI 옵션 표기 수정

lib/tableGenerator.js
#383 [FEAT] .txt출력에도 등수 정보 추가 요청
(https://github.com/oss2025hnu/reposcore-js/commit/5638694bbdfbd3086b02d07d3532a5aef0909f08)
- .txt 형식으로 출력되는 기여자 목록에 등수(rank) 정보가 포함되도록 로직 수정
- 동점자 처리 시 같은 등수를 부여하는 calculateRank() 함수 추가
- 총점 대비 개인 점수의 백분율을 계산하는 calculateRate() 함수 추가
=> [FEAT] .txt출력에 기여자 등수 추가

lib/ChartGenerator.js, lib/csvGenerator.js, lib/tableGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/376
https://github.com/oss2025hnu/reposcore-js/commit/5638694bbdfbd3086b02d07d3532a5aef0909f08
result 폴더에 레포지토리별 분류 및 교수님의 의견인 `_combined.csv`를 `_data.csv`로 나오도록 반영
기존 PR 머지 충돌로 인해 다시 수정 후 PR 작성
=> [FEAT] 결과 확인하는 result 디렉토리 내 레포지토리 별 디렉토리 분리

lib/htmlGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/420
e1f61abfc82b3ac5e1b7641de08098921dde265c
`htmlGenrator.js`에서 생성되는 HTML 파일에 문자 인코딩이 지정되지 않던 문제를 해결하였습니다.
HTML <head> 태그 내에 <meta charset="UTF-8">을 추가하여 한글과 같은 문자가 올바르게 표시되도록 수정하였습니다.
=> [BUG] 인코딩 언어 지정

lib/analyzer.js
https://github.com/oss2025hnu/reposcore-js/issues/443
https://github.com/oss2025hnu/reposcore-js/commit/3c90eb0fcbb8eb569967f766ffdb63fca5dea635
- 참가자가 없는 경우 평균 점수를 0으로 설정
- 평균 점수를 Map 객체로 반환하도록 수정
=> [FEAT] calculateAverageScore 빈 배열 예외 처리 PR

lib/csvGenerator.js, lib/tableGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/476
https://github.com/oss2025hnu/reposcore-js/commit/eda89c4ddcb2d23dfe5c6b7adae21ddfefebc345
- CSV 파일에 doc_ratio 컬럼 추가
- TableGenerator에 문서 비율(%) 컬럼 추가
- 소수점 둘째 자리까지 백분율로 표시
- 그래프, CSV, 텍스트 파일 간 결과물 일관성 유지
=> [FEAT] _combined.csv, .txt 파일 내용에 docRatio(D) 추가해주세요 PR

lib/htmlGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/458
eda89c4ddcb2d23dfe5c6b7adae21ddfefebc345
기존 `htmlGenerator.js`의 `generateHTML`함수에서 올바르지 않게 지정되고 있던 경로를 수정하였습니다.
수정 이후 차트와 표가 올바르게 출력되며, csv파일 다운도 정상적으로 진행되는 모습을 보입니다.
=> [BUG] HTML 표 및 차트 미출력 현상 해결

lib/ChartGenerator.js, lib/chartConfig.js
https://github.com/oss2025hnu/reposcore-js/issues/430 에 대한 PR입니다.
6660d29d162af34eb7e1ad8adc6b25e9ba541353
차트에 있는 막대그래프의 색이 순위에 따라 차이가 있었습니다. 요청자님의 요구사항에 맞게 PR과 Issue의 비율을
확인 가능하도록 막대그래프의 색을 변경하였습니다. (교수님께서 말씀하신 이전 버전의 구체적인 정보도 없어지지 않게 처리하였습니다.)
=> 차트에 issue, pr 구분 요청에 대한 PR

lib/csvGenerator.js, lib/htmlGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/482
https://github.com/oss2025hnu/reposcore-js/commit/6660d29d162af34eb7e1ad8adc6b25e9ba541353
- csvGenerator.js: _combined.csv를 _data.csv로 변경
- htmlGenerator.js: 
- CSV 파일 경로를 _combined.csv에서 _data.csv로 변경
- 다운로드 링크 텍스트를 "Download Combined CSV"에서 "Download Data CSV"로 변경
- html도 안 깨지게 수정 완료.
=> [BUG] _combined.csv 파일이름 다시 수정 PR

lib/htmlGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/499
ac062488e02383631b585744a029d9ec48d2c458 
`generateHTML()` 함수에서 `tabs` 배열을 구성할 때, 저장소가 **2개 이상**일 경우에만 `'total'` 탭을 포함하도록 조건을 추가했습니다.
이를 통해 단일 저장소 분석 시 불필요한 `'total'` 탭이 HTML에 생성되지 않도록 수정했습니다.
=> 장소가 1개일 때도 HTML에 total 분석이 출력되는 문제 해결

lib/htmlGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/489
ac062488e02383631b585744a029d9ec48d2c458
기존 HTML 테이블에서 불필요하게 생성되던 '점수' 행을 제거하였습니다. 
`htmlGenerator.js`의 `generateHTML`의 `tableDataLines[1]`값을 삭제하여 해결하였습니다.
=> HTML 테이블의 불필요한 행 제거

lib/ChartGenerator.js, lib/tableGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/522
https://github.com/oss2025hnu/reposcore-js/commit/c1133f743283e031524688e217c2f37436d6c295
TableGenerator.js:
- 테이블 헤더에서 'feat 비율(%)'을 'feat/bug 비율(%)'로 변경했습니다.
ChartGenerator.js:
- 차트의 데이터 라벨에서 'F'를 'F/B'로 변경했습니다.
- 서브타이틀을 'F: featRatio'에서 'F/B: feat/bug ratio'로 변경하여 더 명확하게 표시했습니다.
=> [REFACTOR] 차트와 .txt결과물에 출력되는 featRatio 수정 PR

lib/htmlGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/518
ac138a381ce3150406f7e4973c8fbf249057b766
`htmlGenerator.js` 에서 `tableDataLines.splice(0, 4);` 을 사용해 중복되는 행(평균/최저/최고 점수)을 삭제하였습니다. 
삭제 후, 테이블이 올바르게 출력되는 모습을 보입니다.
=> html 테이블 중복 출력 제거

lib/htmlGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/528
194aa6b2a43d8480ec97747e40b0314cc454b2f6
generateHTML() 함수에서 저장소 개수를 판단할 때 repositories.length 대신 validRepos.length를 사용하도록 수정했습니다.
이를 통해, 옵션이 포함된 경우에도 저장소가 1개일 때는 total 분석 탭이 생성되지 않도록 로직을 정정하였습니다.
=> [BUG] 저장소가 1개일 때 HTML에 total 분석이 출력되는 문제

lib/csvGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/538
e348462581036e1c6013e9b55a78a85bca097a83
csv파일을 생성하기 위해 `csvContent`의 문자열을 설정하는 과정에서 `(백틱)을 사용후 줄을 바꾸어 작성하여 csv문자열이 의도대로 작성되지 않았습니다. 문자열 사이에 \(역슬래시)를 삽입하여 줄바꿈을 무시하였습니다. 
수정이후 csv파일이 올바르게 생성됩니다.
=> csv 출력 버그 수정

index.js, lib/analyzer.js, lib/csvGenerator.js
https://github.com/oss2025hnu/reposcore-js/issues/544
ad51d0a31e3f0a855606a47c3b4fe95cae13e7ed
-u, --user-name 옵션이 작동하지 않던 문제 해결하였습니다.
- 실명 변환 결과를 scoresMap에 다시 할당하여 모든 출력에 반영
- 차트는 GitHub ID, 텍스트/CSV는 실명으로 분리 (한글 폰트 문제 해결)
- 변수명 일관성 개선 및 중복 코드 제거
문제내용
- 실명 변환 로직은 실행되지만 변환된 결과가 실제 출력에 반영되지 않음
- 실명 변환 결과가 realNameScore에만 저장되고 실제 사용되지 않음
- scoresMap을 다시 계산하면서 실명 변환 결과가 덮어써짐
=> [BUG] -u 옵션 실명 표시 기능 수정

lib/tableGenerator.js
#546
673d06cd6ea3b0992fc4a2ad6072b5e0975bf66c
- `--colored-output` 옵션 개선
- 상위 10%: 🟢 초록색(00ff00)
- 상위 11-30%: 🟡 노란색 (ffff00)
- 상위 31-60%: 🟠 주황색 (ff5a00)
- 상위 61-80%: 🔴 빨간색 (ff0000)
- 하위 81-100%: ⚫ 회색 (808080)
=> --colored-output 옵션 개선

lib/tableGenerator.js
#557 
63d7267
- feat/bug PR, doc PR, typo PR, feat/bug 이슈, doc 이슈 각 항목별 비율(%)을 전체 항목 점수 합(sum) 기준으로 계산하도록 수정했습니다.
- 기존에는 각 항목 비율을 개인 총점으로 나누어 계산해, 비율의 합이 100%가 되지 않는 문제가 있었습니다.
=> 항목별 비율(%)의 합이 100%가 되도록 수정
